### ISSUE TITLE
Benchmark down after sbt upgrade

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/bench#214]
After https://github.com/lampepfl/dotty/pull/9080, we encounter again a file system problem (see #164 #170 #212).

```
[info] loading project definition from /data/workspace/bench/dotty/project/project
[error] java.io.IOException: Permission denied
[error]         at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
[error]         at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
[error]         at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1073)
[error]         at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
[error]         at lmcoursier.internal.shaded.coursier.paths.CachePath.withStructur$
Lock(CachePath.java:136)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withStruct$
reLock(CacheLocks.scala:22)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr$
CacheLocks.scala:39)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$dow$
load$32(FileCache.scala:508)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala$
33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExec$
tor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExe$
utor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) java.io.IOException: Permission denied
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by liufengyun** [comment]
Initial diagnosis seems to be that `coursier` uses home directory for cache. We need change its cache directory to local disk, the same as we do for `SBT`.
